[project]
name = "Decentralized-Insurance-Pool"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/Decentralized-Insurance-Pool/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.peer-to-peer-insurance]
path = "contracts/peer-to-peer-insurance.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
